#!/usr/bin/env python3
"""Is the vertex cone (C^2 x R^3)/G-hat a genuine flat G2 orbifold?
Model R^7 = R^3 (+) H (quaternions).  Left mult by unit quaternions = one SU(2),
right mult = the other.  The associative 3-form for the split:
  phi = dx123 + dx1^w1 + dx2^w2 + dx3^w3
with (w1,w2,w3) the triplet of 2-forms on H generated by one side's multiplication.
The ADE group (2T) must sit on the side FIXING the triplet; base rotations pair with
the side ROTATING it.  We determine sides computationally, build
  G-hat = < 2T ; g_tau = (fiber: triplet-rotation by pi about axis 1) ;
            g_sigma = (fiber: triplet-rotation by pi about axis 3, composed with w in 2O\\2T) >
with matching SO(3) rotations on R^3, and verify phi is preserved by every generator, exactly."""
import sympy as sp
import itertools, sys

s2 = sp.sqrt(2)

# quaternion as 4-vector (1,i,j,k); left/right multiplication matrices
def qmat_left(q):
    a,b,c,d = q
    return sp.Matrix([[a,-b,-c,-d],[b,a,-d,c],[c,d,a,-b],[d,-c,b,a]])
def qmat_right(q):
    a,b,c,d = q
    return sp.Matrix([[a,-b,-c,-d],[b,a,d,-c],[c,-d,a,b],[d,c,-b,a]])

# 2-forms on H: w_i as antisymmetric 4x4 matrices. Candidate triplets: from left or right mult by i,j,k:
# w_i^L(x,y) = <x, L_i y> etc.
I4=sp.eye(4)
Li=qmat_left((0,1,0,0)); Lj=qmat_left((0,0,1,0)); Lk=qmat_left((0,0,0,1))
Ri=qmat_right((0,1,0,0)); Rj=qmat_right((0,0,1,0)); Rk=qmat_right((0,0,0,1))
def two_form(M):  # antisymmetric matrix representing w(x,y)=x^T M y
    return (M - M.T)/2
WL=[two_form(Li),two_form(Lj),two_form(Lk)]
WR=[two_form(Ri),two_form(Rj),two_form(Rk)]

def pullback2(M, W):
    # form w(x,y)=x^T W y pulled back by x->Mx: M^T W M
    return sp.expand(M.T*W*M)

def action_on_triplet(M, Ws):
    # write pullbacks in terms of the triplet: returns 3x3 matrix or None
    A=sp.zeros(3,3)
    for i in range(3):
        P=pullback2(M,Ws[i])
        # solve P = sum_j A[i,j] Ws[j] (the triplet is linearly independent)
        eqs=[]; un=sp.symbols(f'c0:3')
        R=P - (un[0]*Ws[0]+un[1]*Ws[1]+un[2]*Ws[2])
        sol=sp.solve([e for e in R], list(un), dict=True)
        if not sol: return None
        for j in range(3): A[i,j]=sp.nsimplify(sol[0][un[j]])
    return A

# which side fixes WR? left multiplication should fix right-generated forms:
u=( sp.Rational(1,2), sp.Rational(1,2), sp.Rational(1,2), sp.Rational(1,2) )  # element of 2T
ML=qmat_left(u); MR=qmat_right(u)
AL=action_on_triplet(ML,WR)
AR=action_on_triplet(MR,WR)
print("left-mult action on right-triplet:\n",AL)
print("right-mult action on right-triplet:\n",AR)
# expect: left-mult = identity (fixes), right-mult = nontrivial rotation
fix_side = 'left' if AL==sp.eye(3) else ('right' if AR==sp.eye(3) else None)
print("side fixing the (right-generated) triplet:", fix_side)
assert fix_side=='left'

# So: 2T = LEFT multiplications (fixes triplet => pure ADE);
#     base-paired rotations = RIGHT multiplications, with SO(3) matrix = action on triplet.
# Generators:
gens={}
# 2T generators: u=(1+i+j+k)/2 and i
gens['t1 in 2T'] = ('L', u, None)
gens['t2 in 2T'] = ('L', (0,1,0,0), None)
# g_tau: right-mult by i (pi-rotation of triplet about axis 1), no left part
gens['g_tau']    = ('R', (0,1,0,0), None)
# g_sigma: right-mult by k (pi about axis 3) composed with LEFT mult by w=(1+i)/sqrt2 in 2O\2T
w=( 1/s2, 1/s2, 0, 0 )
gens['g_sigma']  = ('RL', (0,0,0,1), w)

# check w normalizes 2T but is not in 2T: |w| entries not half-integers -> not in 2T; w i w^-1 = i;
# w j w^-1 = ? compute: conj by w maps j -> (1+i) j (1-i)/2 = (j + i j - j i - i j i)/2 = (j+k+k+... compute numerically
def qmul(p,q):
    a1,b1,c1,d1=p; a2,b2,c2,d2=q
    return (a1*a2-b1*b2-c1*c2-d1*d2,
            a1*b2+b1*a2+c1*d2-d1*c2,
            a1*c2-b1*d2+c1*a2+d1*b2,
            a1*d2+b1*c2-c1*b2+d1*a2)
def qconj(q): return (q[0],-q[1],-q[2],-q[3])
wjw=qmul(qmul(w,(0,0,1,0)),qconj(w))
print("w j w^{-1} =", [sp.nsimplify(sp.simplify(x)) for x in wjw], " (should be in 2T: expect ±k or similar)")

# Build 7x7 matrices: coordinates (x1,x2,x3, q0,q1,q2,q3)
def seven(gen):
    kind, r, l = gen
    if kind=='L':
        M4 = qmat_left(r); R3 = sp.eye(3)
    elif kind=='R':
        M4 = qmat_right(qconj(r))  # q -> q r^{-1}? convention: use right mult by r
        M4 = qmat_right(r)
        R3 = action_on_triplet(qmat_right(r), WR)
    else:
        M4 = qmat_left(l)*qmat_right(r)
        R3 = action_on_triplet(qmat_right(r), WR)  # left part doesn't rotate triplet
    M=sp.zeros(7,7)
    M[0:3,0:3]=R3
    M[3:7,3:7]=M4
    return sp.Matrix(M)

# associative 3-form phi = dx123 + sum_i dx_i ^ w_i  (w_i = right-generated triplet on H-block)
# encode phi as dict on index triples (i<j<k) over 0..6; H-block indices 3..6
phi={}
phi[(0,1,2)]=sp.Integer(1)
for i in range(3):
    W=WR[i]
    for a in range(4):
        for b in range(a+1,4):
            c=2*W[a,b]  # w = sum_{a<b} (2W[a,b]) dx_a ^ dx_b since W antisym encodes w(x,y)=x^T W y
            if c!=0:
                idx=tuple(sorted((i,3+a,3+b)))
                # sign from sorting (i first always since i<3<=3+a) -> no swap needed
                phi[idx]=phi.get(idx,0)+c
def pullback3(M,phi):
    out={}
    n=7
    for (i,j,k),c in phi.items():
        # dx_i^dx_j^dx_k pulled back: sum over a<b<c of det of 3x3 minor
        for a in range(n):
            for b in range(a+1,n):
                for cc in range(b+1,n):
                    d=sp.det(sp.Matrix([[M[i,a],M[i,b],M[i,cc]],
                                        [M[j,a],M[j,b],M[j,cc]],
                                        [M[k,a],M[k,b],M[k,cc]]]))
                    if d!=0:
                        out[(a,b,cc)]=sp.simplify(out.get((a,b,cc),0)+c*d)
    return {k2:sp.simplify(v) for k2,v in out.items() if sp.simplify(v)!=0}

ok=True
for name,gen in gens.items():
    M=seven(gen)
    pb=pullback3(M,phi)
    same = (set(pb.keys())==set(k2 for k2,v in phi.items() if v!=0) and
            all(sp.simplify(pb[k2]-phi[k2])==0 for k2 in pb))
    print(("PASS " if same else "FAIL ")+f"{name}: preserves associative 3-form phi")
    ok = ok and same
    # also orientation/orthogonality sanity
    assert sp.simplify(M.T*M-sp.eye(7))==sp.zeros(7,7)

# group order and strata
import itertools as it
def key(M): return tuple(sp.nsimplify(sp.simplify(x)) for x in M)
Ms=[seven(g) for g in gens.values()]
seen={key(sp.eye(7)): sp.eye(7)}
frontier=[sp.eye(7)]
while frontier:
    nf=[]
    for X in frontier:
        for G in Ms:
            Y=sp.expand(X*G)
            Y=Y.applyfunc(sp.nsimplify)
            k2=key(Y)
            if k2 not in seen:
                seen[k2]=Y; nf.append(Y)
    frontier=nf
print("order of G-hat:", len(seen))
# isolated fixed point: elements fixing only origin vs strata
from sympy import Matrix
fixdims={}
for k2,M in seen.items():
    if M==sp.eye(7): continue
    d=(M-sp.eye(7)).nullspace()
    fixdims[len(d)]=fixdims.get(len(d),0)+1
print("fixed-subspace dimension distribution over nontrivial elements:", fixdims)
print("OVERALL:", "PASS — the cone is a flat G2 orbifold" if ok else "FAIL")
sys.exit(0 if ok else 1)
